# Generated by Django 5.0.6 on 2024-08-02 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Заголовок статьи', max_length=100, verbose_name='Заголовок')),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True, verbose_name='slug')),
                ('body', models.TextField(blank=True, max_length=250, null=True, verbose_name='Cодержимое')),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog/images', verbose_name='Изображение(превью)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания(записи в БД)')),
                ('is_published', models.BooleanField(default=True, verbose_name='Признак публикации')),
                ('views_count', models.IntegerField(default=0, verbose_name='Просмотры')),
            ],
        ),
    ]
